services:
  converter:
    volumes:
      # These volumes hinder pytest in development environment
      # since pytest moves these directories to evacuate for test.
      - ./config.yml:/workspace/config.yml
      - ./csvconverttable:/workspace/csvconverttable
      - ./csvinput:/workspace/csvinput
      - ./csvoutput:/workspace/csvoutput
