name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  call-workflow-test:
    uses: yukihiko-shinoda/invoke-lint/.github/workflows/reusable-test.yml@main
    with:
      support-python-versions: "[ '3.13', '3.12', '3.11', '3.10', '3.9' ]"
  call-workflow-lint:
    uses: yukihiko-shinoda/invoke-lint/.github/workflows/reusable-lint.yml@main
